# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'SnapKit', '~> 0.15.0'
pod ‘EasyAnimation’

target 'Just Cook' do

end

